version: "3.8"
services:
  app:
    build:
      context: ..
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=develop
      - DB_URL=${DB_URL}
    env_file:
      - ../.env
    volumes:
      - ../:/app
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
